apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/red-hat-hawtio-operator.hawtio-operator: ''
  name: red-hat-hawtio-operator
  namespace: hawtio-operator
spec:
  channel: stable-v1
  name: red-hat-hawtio-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: red-hat-hawtio-operator.v1.0.2